AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'spec/*'

# turning off documentation for module
Documentation:
  Enabled: false

# frozen string literal alert
Style/FrozenStringLiteralComment:
  Enabled: false