version: '3'

services:
  web:
    build:
      context: .
    environment:
      DATABASE_URL: db
    command: >
      bash -c "bin/rake db:create db:migrate db:seed
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    networks:
      - railsapp-network
  db:
    image: postgres
    # ports:
    #   - "5432:5432"
    networks:
      - railsapp-network

networks:
  railsapp-network:
    driver: bridge
